User.delete_all
Product.delete_all
Store.delete_all
Review.delete_all
CartItem.delete_all
Order.delete_all

user = User.create(id: 581965828, email: 'kg1fsq04tetqirwv@email.com', password: 'password')
image = Image.create(data: "jfdklajf", mimetype: "kdfjsl", encoding: "kfdjaslj")
icon = Image.create(user_id: 581965828, shop_id: 33497523, icon: nil)
shop = Store.create(id: 33497523, shop_name: 'SonyaFlemingArt', user_id: 581965828, creation_tsz: 1640325141, title: nil, announcement: nil, currency_code: 'AUD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640325141, listing_active_count: 1, digital_listing_count: 0, login_name: 'kg1fsq04tetqirwv', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/SonyaFlemingArt?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['de'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: false, is_opted_in_to_buyer_promise: false, is_shop_us_based: false, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 60189405, email: 'jolenelenhart@email.com', password: 'password')
image = Image.create(user_id: 60189405, shop_id: 33497501, image: nil)
icon = Image.create(user_id: 60189405, shop_id: 33497501, icon: nil)
shop = Store.create(id: 33497501, shop_name: 'MargaretDarlingtonUS', user_id: 60189405, creation_tsz: 1640325081, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640325081, listing_active_count: 1, digital_listing_count: 1, login_name: 'jolenelenhart', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/MargaretDarlingtonUS?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 91201894, email: 'patbadams49@email.com', password: 'password')
image = Image.create(user_id: 91201894, shop_id: 33497477, image: nil)
icon = Image.create(user_id: 91201894, shop_id: 33497477, icon: nil)
shop = Store.create(id: 33497477, shop_name: 'tammymauk', user_id: 91201894, creation_tsz: 1640324942, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640325086, listing_active_count: 1, digital_listing_count: 1, login_name: 'patbadams49', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/tammymauk?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)
Product.create(id: 1147301731, store_id: store.id, state: 'unavailable', sku: [], is_vintage: false, results_per_page: 100, page_number: 1)


user = User.create(id: 181541356, email: '6di20ex3@email.com', password: 'password')
image = Image.create(user_id: 181541356, shop_id: 33497471, image: nil)
icon = Image.create(user_id: 181541356, shop_id: 33497471, icon: nil)
shop = Store.create(id: 33497471, shop_name: 'DawnEDesign', user_id: 181541356, creation_tsz: 1640324761, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324761, listing_active_count: 1, digital_listing_count: 1, login_name: '6di20ex3', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/DawnEDesign?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)
Product.create(id: 1147301411, store_id: store.id, state: 'active', user_id: 181541356, category_id: nil, title: 'Landscape decoration painting restaurant background wall', description: 'Landscape decoration painting restaurant background wall', creation_tsz: 1640325321, ending_tsz: 1650776121, original_creation_tsz: 1640324522, last_modified_tsz: 1640339250, price: '87.00', currency_code: 'USD', quantity: 13, sku: [], tags: ['Adornment picture'], materials: [], shop_section_id: nil, featured_rank: nil, state_tsz: 1640339250, url: 'https://www.etsy.com/listing/1147301411/landscape-decoration-painting-restaurant?utm_source=educationalclone&utm_medium=api&utm_campaign=api', views: 5, num_favorers: 0, shipping_template_id: nil, processing_min: nil, processing_max: nil, who_made: 'i_did', is_supply: 'false', when_made: 'made_to_order', item_weight: nil, item_weight_unit: 'oz', item_length: nil, item_width: nil, item_height: nil, item_dimensions_unit: 'in', is_private: false, style: nil, non_taxable: false, is_customizable: false, is_digital: true, file_data: '1 JPG', should_auto_renew: true, language: 'en-US', has_variations: false, taxonomy_id: 1027, taxonomy_path: ['Home & Living', 'Home Decor', 'Wall Decor'], used_manufacturer: false, is_vintage: false, results_per_page: 100, page_number: 1)
Image.create(id: 3600223129, product_id: 1147301411, user_id: user.id, store_id: store.id, hex_code: '9F9387', red: 159, green: 147, blue: 135, hue: 30, saturation: 15, brightness: 62, is_black_and_white: false, creation_tsz: 1640324522, rank: 1, full_height: 3000, full_width: 1987, image_small: 'https://i.etsystatic.com/33497471/r/il/01e248/3600223129/il_75x75.3600223129_5qvp.jpg', image_medium: 'https://i.etsystatic.com/33497471/r/il/01e248/3600223129/il_170x135.3600223129_5qvp.jpg', image_large: 'https://i.etsystatic.com/33497471/r/il/01e248/3600223129/il_570xN.3600223129_5qvp.jpg', image_full: 'https://i.etsystatic.com/33497471/r/il/01e248/3600223129/il_fullxfull.3600223129_5qvp.jpg')


user = User.create(id: 586339735, email: 'lt6nh67gzu0q79pz@email.com', password: 'password')
image = Image.create(user_id: 586339735, shop_id: 33497463, image: nil)
icon = Image.create(user_id: 586339735, shop_id: 33497463, icon: nil)
shop = Store.create(id: 33497463, shop_name: 'SSDeeDeeSoo', user_id: 586339735, creation_tsz: 1640324798, title: nil, announcement: nil, currency_code: 'AUD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324798, listing_active_count: 1, digital_listing_count: 0, login_name: 'lt6nh67gzu0q79pz', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/SSDeeDeeSoo?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['de'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: false, is_opted_in_to_buyer_promise: false, is_shop_us_based: false, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 581964668, email: 'pclrr2z5cdjm051u@email.com', password: 'password')
image = Image.create(user_id: 581964668, shop_id: 33497449, image: nil)
icon = Image.create(user_id: 581964668, shop_id: 33497449, icon: nil)
shop = Store.create(id: 33497449, shop_name: 'CheekyandLulu', user_id: 581964668, creation_tsz: 1640324808, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324808, listing_active_count: 1, digital_listing_count: 1, login_name: 'pclrr2z5cdjm051u', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/CheekyandLulu?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 581964576, email: 'g1ztcfizv7bvwh6d@email.com', password: 'password')
image = Image.create(user_id: 581964576, shop_id: 33497441, image: nil)
icon = Image.create(user_id: 581964576, shop_id: 33497441, icon: nil)
shop = Store.create(id: 33497441, shop_name: 'SkyeEvansTreasures', user_id: 581964576, creation_tsz: 1640325040, title: nil, announcement: nil, currency_code: 'AUD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640325040, listing_active_count: 1, digital_listing_count: 0, login_name: 'g1ztcfizv7bvwh6d', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/SkyeEvansTreasures?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['de'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: false, is_opted_in_to_buyer_promise: false, is_shop_us_based: false, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 57346288, email: 'shaniaof4@email.com', password: 'password')
image = Image.create(user_id: 57346288, shop_id: 33497431, image: nil)
icon = Image.create(user_id: 57346288, shop_id: 33497431, icon: nil)
shop = Store.create(id: 33497431, shop_name: 'CrystieMongiat', user_id: 57346288, creation_tsz: 1640324389, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324389, listing_active_count: 1, digital_listing_count: 0, login_name: 'shaniaof4', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/CrystieMongiat?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 285233022, email: 'eqpn4yah@email.com', password: 'password')
image = Image.create(user_id: 285233022, shop_id: 33497403, image: nil)
icon = Image.create(user_id: 285233022, shop_id: 33497403, icon: nil)
shop = Store.create(id: 33497403, shop_name: 'JamieVonkCo', user_id: 285233022, creation_tsz: 1640324319, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640325062, listing_active_count: 1, digital_listing_count: 1, login_name: 'eqpn4yah', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/JamieVonkCo?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 581961614, email: 'gu7dnrrhhlnee8n7@email.com', password: 'password')
image = Image.create(user_id: 581961614, shop_id: 33497397, image: nil)
icon = Image.create(user_id: 581961614, shop_id: 33497397, icon: nil)
shop = Store.create(id: 33497397, shop_name: 'Xipkolaen', user_id: 581961614, creation_tsz: 1640324940, title: nil, announcement: nil, currency_code: 'EUR', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324940, listing_active_count: 1, digital_listing_count: 0, login_name: 'gu7dnrrhhlnee8n7', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/Xipkolaen?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: false, is_opted_in_to_buyer_promise: false, is_shop_us_based: false, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)
Product.create(id: 1147300057, store_id: store.id, state: 'active', user_id: 581961614, category_id: nil, title: 'Ring 14K Solid Gold for Women Kyklos Jewelry - February Birthstone Stacking Minimalist Dainty', description: '14K Elegant', creation_tsz: 1640324940, ending_tsz: 1650775740, original_creation_tsz: 1640324221, last_modified_tsz: 1640327312, price: '6500.00', currency_code: 'EUR', quantity: 12, sku: [], tags: ['silver bracelet', 'silver necklace', 'silver anklet', 'gold', 'gold jewellery', 'gold ring', 'gold earring', 'gold bracelet', 'gold necklace', 'gold anklet', 'rose gold', 'rose gold jewellery', 'rose gold ring'], materials: [], shop_section_id: nil, featured_rank: nil, state_tsz: 1640324221, url: 'https://www.etsy.com/listing/1147300057/ring-14k-solid-gold-for-women-kyklos?utm_source=educationalclone&utm_medium=api&utm_campaign=api', views: 2, num_favorers: 0, shipping_template_id: nil, processing_min: 1, processing_max: 3, who_made: 'i_did', is_supply: 'false', when_made: '2020_2021', item_weight: nil, item_weight_unit: 'g', item_length: nil, item_width: nil, item_height: nil, item_dimensions_unit: 'mm', is_private: false, style: nil, non_taxable: false, is_customizable: false, is_digital: false, file_data: '', should_auto_renew: true, language: 'en-US', has_variations: true, taxonomy_id: 1240, taxonomy_path: ['Jewelry', 'Rings', 'Statement Rings'], used_manufacturer: false, is_vintage: false, results_per_page: 100, page_number: 1)
Image.create(id: 3552579490, product_id: 1147300057, user_id: user.id, store_id: store.id, hex_code: '7A4F8B', red: 122, green: 79, blue: 139, hue: 283, saturation: 43, brightness: 54, is_black_and_white: false, creation_tsz: 1640324221, rank: 1, full_height: 2000, full_width: 2266, image_small: 'https://i.etsystatic.com/33497397/r/il/763a7a/3552579490/il_75x75.3552579490_ppvq.jpg', image_medium: 'https://i.etsystatic.com/33497397/r/il/763a7a/3552579490/il_170x135.3552579490_ppvq.jpg', image_large: 'https://i.etsystatic.com/33497397/r/il/763a7a/3552579490/il_570xN.3552579490_ppvq.jpg', image_full: 'https://i.etsystatic.com/33497397/r/il/763a7a/3552579490/il_fullxfull.3552579490_ppvq.jpg')
Image.create(id: 3600219699, product_id: 1147300057, user_id: user.id, store_id: store.id, hex_code: 'AB6E78', red: 171, green: 110, blue: 120, hue: 350, saturation: 35, brightness: 67, is_black_and_white: false, creation_tsz: 1640324221, rank: 2, full_height: 2447, full_width: 2000, image_small: 'https://i.etsystatic.com/33497397/r/il/2eb465/3600219699/il_75x75.3600219699_rj3v.jpg', image_medium: 'https://i.etsystatic.com/33497397/r/il/2eb465/3600219699/il_170x135.3600219699_rj3v.jpg', image_large: 'https://i.etsystatic.com/33497397/r/il/2eb465/3600219699/il_570xN.3600219699_rj3v.jpg', image_full: 'https://i.etsystatic.com/33497397/r/il/2eb465/3600219699/il_fullxfull.3600219699_rj3v.jpg')


user = User.create(id: 130185384, email: '9acs8ozd@email.com', password: 'password')
image = Image.create(user_id: 130185384, shop_id: 33497395, image: nil)
icon = Image.create(user_id: 130185384, shop_id: 33497395, icon: nil)
shop = Store.create(id: 33497395, shop_name: 'LylePetrusakDesigns', user_id: 130185384, creation_tsz: 1640324668, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324668, listing_active_count: 1, digital_listing_count: 0, login_name: '9acs8ozd', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/LylePetrusakDesigns?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 280196095, email: 'm8v1eh4e@email.com', password: 'password')
image = Image.create(user_id: 280196095, shop_id: 33497383, image: nil)
icon = Image.create(user_id: 280196095, shop_id: 33497383, icon: nil)
shop = Store.create(id: 33497383, shop_name: 'DedraFinds', user_id: 280196095, creation_tsz: 1640324147, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324972, listing_active_count: 1, digital_listing_count: 1, login_name: 'm8v1eh4e', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/DedraFinds?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)
Product.create(id: 1147298683, store_id: store.id, state: 'active', user_id: 280196095, category_id: nil, title: 'Meadow flower landscape painting decorative painting', description: 'Meadow flower landscape painting decorative painting', creation_tsz: 1640325600, ending_tsz: 1650776400, original_creation_tsz: 1640323934, last_modified_tsz: 1640352643, price: '84.00', currency_code: 'USD', quantity: 12, sku: [], tags: ['Adornment picture'], materials: [], shop_section_id: nil, featured_rank: nil, state_tsz: 1640352643, url: 'https://www.etsy.com/listing/1147298683/meadow-flower-landscape-painting?utm_source=educationalclone&utm_medium=api&utm_campaign=api', views: 7, num_favorers: 0, shipping_template_id: nil, processing_min: nil, processing_max: nil, who_made: 'i_did', is_supply: 'false', when_made: 'made_to_order', item_weight: nil, item_weight_unit: 'oz', item_length: nil, item_width: nil, item_height: nil, item_dimensions_unit: 'in', is_private: false, style: nil, non_taxable: false, is_customizable: false, is_digital: true, file_data: '1 JPG', should_auto_renew: true, language: 'en-US', has_variations: false, taxonomy_id: 1027, taxonomy_path: ['Home & Living', 'Home Decor', 'Wall Decor'], used_manufacturer: false, is_vintage: false, results_per_page: 100, page_number: 1)
Image.create(id: 3552575696, product_id: 1147298683, user_id: user.id, store_id: store.id, hex_code: '758B29', red: 117, green: 139, blue: 41, hue: 73, saturation: 70, brightness: 54, is_black_and_white: false, creation_tsz: 1640323934, rank: 1, full_height: 1125, full_width: 2000, image_small: 'https://i.etsystatic.com/33497383/r/il/a97ff6/3552575696/il_75x75.3552575696_b3mx.jpg', image_medium: 'https://i.etsystatic.com/33497383/r/il/a97ff6/3552575696/il_170x135.3552575696_b3mx.jpg', image_large: 'https://i.etsystatic.com/33497383/r/il/a97ff6/3552575696/il_570xN.3552575696_b3mx.jpg', image_full: 'https://i.etsystatic.com/33497383/r/il/a97ff6/3552575696/il_fullxfull.3552575696_b3mx.jpg')


user = User.create(id: 406423106, email: 'azctwrttxtsda8il@email.com', password: 'password')
image = Image.create(user_id: 406423106, shop_id: 33497367, image: nil)
icon = Image.create(user_id: 406423106, shop_id: 33497367, icon: nil)
shop = Store.create(id: 33497367, shop_name: 'CarolynDrak', user_id: 406423106, creation_tsz: 1640324169, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640325115, listing_active_count: 1, digital_listing_count: 1, login_name: 'azctwrttxtsda8il', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/CarolynDrak?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)
Product.create(id: 1147298947, store_id: store.id, state: 'active', user_id: 406423106, category_id: nil, title: 'Cartoon panda picnic graphics wallpaper decoration painting', description: 'Cartoon panda picnic graphics wallpaper decoration painting', creation_tsz: 1640333679, ending_tsz: 1650784479, original_creation_tsz: 1640323991, last_modified_tsz: 1640367752, price: '86.00', currency_code: 'USD', quantity: 1, sku: [], tags: ['art'], materials: [], shop_section_id: nil, featured_rank: nil, state_tsz: 1640333765, url: 'https://www.etsy.com/listing/1147298947/cartoon-panda-picnic-graphics-wallpaper?utm_source=educationalclone&utm_medium=api&utm_campaign=api', views: 34, num_favorers: 0, shipping_template_id: nil, processing_min: nil, processing_max: nil, who_made: 'i_did', is_supply: 'false', when_made: 'made_to_order', item_weight: nil, item_weight_unit: 'oz', item_length: nil, item_width: nil, item_height: nil, item_dimensions_unit: 'in', is_private: false, style: nil, non_taxable: false, is_customizable: false, is_digital: true, file_data: '1 JPG', should_auto_renew: true, language: 'en-US', has_variations: false, taxonomy_id: 1027, taxonomy_path: ['Home & Living', 'Home Decor', 'Wall Decor'], used_manufacturer: false, is_vintage: false, results_per_page: 100, page_number: 1)
Image.create(id: 3600214893, product_id: 1147298947, user_id: user.id, store_id: store.id, hex_code: '8D967D', red: 141, green: 150, blue: 125, hue: 82, saturation: 16, brightness: 58, is_black_and_white: false, creation_tsz: 1640323991, rank: 1, full_height: 3000, full_width: 1432, image_small: 'https://i.etsystatic.com/33497367/r/il/221590/3600214893/il_75x75.3600214893_to8s.jpg', image_medium: 'https://i.etsystatic.com/33497367/r/il/221590/3600214893/il_170x135.3600214893_to8s.jpg', image_large: 'https://i.etsystatic.com/33497367/r/il/221590/3600214893/il_570xN.3600214893_to8s.jpg', image_full: 'https://i.etsystatic.com/33497367/r/il/221590/3600214893/il_fullxfull.3600214893_to8s.jpg')


user = User.create(id: 581962966, email: 'o3s8rnp3yfijcg1k@email.com', password: 'password')
image = Image.create(user_id: 581962966, shop_id: 33497363, image: nil)
icon = Image.create(user_id: 581962966, shop_id: 33497363, icon: nil)
shop = Store.create(id: 33497363, shop_name: 'ggSonaliMendis', user_id: 581962966, creation_tsz: 1640324052, title: nil, announcement: nil, currency_code: 'AUD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324052, listing_active_count: 1, digital_listing_count: 0, login_name: 'o3s8rnp3yfijcg1k', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/ggSonaliMendis?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['de'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: false, is_opted_in_to_buyer_promise: false, is_shop_us_based: false, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 165402878, email: 'dioftx7t@email.com', password: 'password')
image = Image.create(user_id: 165402878, shop_id: 33497323, image: nil)
icon = Image.create(user_id: 165402878, shop_id: 33497323, icon: nil)
shop = Store.create(id: 33497323, shop_name: 'AnalizaShop', user_id: 165402878, creation_tsz: 1640323576, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640324564, listing_active_count: 1, digital_listing_count: 1, login_name: 'dioftx7t', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/AnalizaShop?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)
Product.create(id: 1133347394, store_id: store.id, state: 'active', user_id: 165402878, category_id: nil, title: 'Romantic landscape decorative paintings', description: 'Romantic landscape decorative paintings', creation_tsz: 1640348253, ending_tsz: 1650799053, original_creation_tsz: 1640323388, last_modified_tsz: 1640348253, price: '86.00', currency_code: 'USD', quantity: 10, sku: [], tags: ['Adornment picture'], materials: [], shop_section_id: nil, featured_rank: nil, state_tsz: 1640323388, url: 'https://www.etsy.com/listing/1133347394/romantic-landscape-decorative-paintings?utm_source=educationalclone&utm_medium=api&utm_campaign=api', views: 8, num_favorers: 0, shipping_template_id: nil, processing_min: nil, processing_max: nil, who_made: 'i_did', is_supply: 'false', when_made: 'made_to_order', item_weight: nil, item_weight_unit: 'oz', item_length: nil, item_width: nil, item_height: nil, item_dimensions_unit: 'in', is_private: false, style: nil, non_taxable: false, is_customizable: false, is_digital: true, file_data: '1 JPG', should_auto_renew: true, language: 'en-US', has_variations: false, taxonomy_id: 1027, taxonomy_path: ['Home & Living', 'Home Decor', 'Wall Decor'], used_manufacturer: false, is_vintage: false, results_per_page: 100, page_number: 1)
Image.create(id: 3552569440, product_id: 1133347394, user_id: user.id, store_id: store.id, hex_code: '9D6862', red: 157, green: 104, blue: 98, hue: 6, saturation: 37, brightness: 61, is_black_and_white: false, creation_tsz: 1640323388, rank: 1, full_height: 3000, full_width: 1647, image_small: 'https://i.etsystatic.com/33497323/r/il/a92ab2/3552569440/il_75x75.3552569440_mgfw.jpg', image_medium: 'https://i.etsystatic.com/33497323/r/il/a92ab2/3552569440/il_170x135.3552569440_mgfw.jpg', image_large: 'https://i.etsystatic.com/33497323/r/il/a92ab2/3552569440/il_570xN.3552569440_mgfw.jpg', image_full: 'https://i.etsystatic.com/33497323/r/il/a92ab2/3552569440/il_fullxfull.3552569440_mgfw.jpg')


user = User.create(id: 130740033, email: 'wsdlhsou@email.com', password: 'password')
image = Image.create(user_id: 130740033, shop_id: 33497317, image: nil)
icon = Image.create(user_id: 130740033, shop_id: 33497317, icon: nil)
shop = Store.create(id: 33497317, shop_name: 'MeondraTaylo', user_id: 130740033, creation_tsz: 1640323622, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640323622, listing_active_count: 0, digital_listing_count: 0, login_name: 'wsdlhsou', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/MeondraTaylo?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 586336871, email: 'bzw2d5qos67lwbkm@email.com', password: 'password')
image = Image.create(user_id: 586336871, shop_id: 33497315, image: nil)
icon = Image.create(user_id: 586336871, shop_id: 33497315, icon: nil)
shop = Store.create(id: 33497315, shop_name: 'RebeccaTaita', user_id: 586336871, creation_tsz: 1640323634, title: nil, announcement: nil, currency_code: 'AUD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640323634, listing_active_count: 0, digital_listing_count: 0, login_name: 'bzw2d5qos67lwbkm', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/RebeccaTaita?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['de'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: false, is_opted_in_to_buyer_promise: false, is_shop_us_based: false, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 68401889, email: 'annmarkham1@email.com', password: 'password')
image = Image.create(user_id: 68401889, shop_id: 33497303, image: nil)
icon = Image.create(user_id: 68401889, shop_id: 33497303, icon: nil)
shop = Store.create(id: 33497303, shop_name: 'KathyWashingtonStore', user_id: 68401889, creation_tsz: 1640323672, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640323672, listing_active_count: 0, digital_listing_count: 0, login_name: 'annmarkham1', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/KathyWashingtonStore?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 586336349, email: 'xcbmfjxolkg0rrr1@email.com', password: 'password')
image = Image.create(user_id: 586336349, shop_id: 33497291, image: nil)
icon = Image.create(user_id: 586336349, shop_id: 33497291, icon: 'https://i.etsystatic.com/isla/7f96e2/52480966/isla_fullxfull.52480966_1wpfr0wr.jpg?version=0')
shop = Store.create(id: 33497291, shop_name: 'BosskevinStudio', user_id: 586336349, creation_tsz: 1640323940, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640323940, listing_active_count: 1, digital_listing_count: 0, login_name: 'xcbmfjxolkg0rrr1', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/BosskevinStudio?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: 'https://i.etsystatic.com/isla/7f96e2/52480966/isla_fullxfull.52480966_1wpfr0wr.jpg?version=0', is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


user = User.create(id: 79715617, email: 'lindseyrast6@email.com', password: 'password')
image = Image.create(user_id: 79715617, shop_id: 33497277, image: nil)
icon = Image.create(user_id: 79715617, shop_id: 33497277, icon: nil)
shop = Store.create(id: 33497277, shop_name: 'MelissaurnerSmi', user_id: 79715617, creation_tsz: 1640323333, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640323333, listing_active_count: 1, digital_listing_count: 1, login_name: 'lindseyrast6', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/MelissaurnerSmi?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)
Product.create(id: 1147293999, store_id: store.id, state: 'active', user_id: 79715617, category_id: nil, title: 'White clouds sky background wall hanging paintings Chinese murals living room bedroom decorative paintings', description: 'White clouds sky background wall hanging paintings Chinese murals living room bedroom decorative paintings', creation_tsz: 1640350599, ending_tsz: 1650801399, original_creation_tsz: 1640322988, last_modified_tsz: 1640367781, price: '83.00', currency_code: 'USD', quantity: 14, sku: [], tags: ['Hang a picture'], materials: [], shop_section_id: nil, featured_rank: nil, state_tsz: 1640324895, url: 'https://www.etsy.com/listing/1147293999/white-clouds-sky-background-wall-hanging?utm_source=educationalclone&utm_medium=api&utm_campaign=api', views: 4, num_favorers: 0, shipping_template_id: nil, processing_min: nil, processing_max: nil, who_made: 'i_did', is_supply: 'false', when_made: 'made_to_order', item_weight: nil, item_weight_unit: 'oz', item_length: nil, item_width: nil, item_height: nil, item_dimensions_unit: 'in', is_private: false, style: nil, non_taxable: false, is_customizable: false, is_digital: true, file_data: '1 JPG', should_auto_renew: true, language: 'en-US', has_variations: false, taxonomy_id: 2078, taxonomy_path: ['Art & Collectibles', 'Prints', 'Digital Prints'], used_manufacturer: false, is_vintage: false, results_per_page: 100, page_number: 1)
Image.create(id: 3600204523, product_id: 1147293999, user_id: user.id, store_id: store.id, hex_code: 'ABBAD7', red: 171, green: 186, blue: 215, hue: 220, saturation: 20, brightness: 84, is_black_and_white: false, creation_tsz: 1640322988, rank: 1, full_height: 3000, full_width: 1649, image_small: 'https://i.etsystatic.com/33497277/r/il/5f91c9/3600204523/il_75x75.3600204523_6agg.jpg', image_medium: 'https://i.etsystatic.com/33497277/r/il/5f91c9/3600204523/il_170x135.3600204523_6agg.jpg', image_large: 'https://i.etsystatic.com/33497277/r/il/5f91c9/3600204523/il_570xN.3600204523_6agg.jpg', image_full: 'https://i.etsystatic.com/33497277/r/il/5f91c9/3600204523/il_fullxfull.3600204523_6agg.jpg')


user = User.create(id: 311478109, email: 'ucftwoin@email.com', password: 'password')
image = Image.create(user_id: 311478109, shop_id: 33497275, image: nil)
icon = Image.create(user_id: 311478109, shop_id: 33497275, icon: nil)
shop = Store.create(id: 33497275, shop_name: 'ChristinaFryByDelee', user_id: 311478109, creation_tsz: 1640323513, title: nil, announcement: nil, currency_code: 'USD', is_vacation: false, vacation_message: nil, sale_message: nil, digital_sale_message: nil, last_updated_tsz: 1640323513, listing_active_count: 0, digital_listing_count: 0, login_name: 'ucftwoin', accepts_custom_requests: false, policy_welcome: nil, policy_payment: nil, policy_shipping: nil, policy_refunds: nil, policy_additional: nil, policy_seller_info: nil, policy_updated_tsz: 0, policy_has_private_receipt_info: false, vacation_autoreply: nil, url: 'https://www.etsy.com/shop/ChristinaFryByDelee?utm_source=educationalclone&utm_medium=api&utm_campaign=api', image_url_760x100: nil, num_favorers: 0, languages: ['en-US'], upcoming_local_event_id: nil, icon_url_fullxfull: nil, is_using_structured_policies: false, has_onboarded_structured_policies: false, has_unstructured_policies: false, include_dispute_form_link: false, is_direct_checkout_onboarded: true, policy_privacy: nil, is_calculated_eligible: true, is_opted_in_to_buyer_promise: false, is_shop_us_based: true, results_per_page: 100, page_number: 1, image_id: image.id, icon_id: icon.id)


